Define _GNU_SOURCE
Define _GNU_SOURCE so that asprintf is prototyped

execute.c: In function ‘view_logfile_execute’:
execute.c:250:7: warning: implicit declaration of function ‘asprintf’ [-Wimplicit-function-declaration]
trayicon.c: In function ‘aboutDlgProc’:
trayicon.c:115:11: warning: implicit declaration of function ‘asprintf’ [-Wimplicit-function-declaration]